# libraries_registry.yaml
# Registry of adapters and their dependencies

libraries:
  # iisignature:
  #   type: python
  #   script: "adapters/python/run_iisignature.py"
  #   extras:
  #     - iisignature
  #   operations:
  #     - signature
  #     - logsignature

  pysiglib:
    type: python
    script: "adapters/python/run_pysiglib.py"
    extras:
      - pysiglib
    backends:
      - name: cpu
        env:
          JAX_PLATFORM_NAME: cpu
      - name: gpu
        env:
          JAX_PLATFORM_NAME: gpu
    operations:
      - signature
      - logsignature
      - sigdiff
      - branchedsignature_nonplanar
      - branchedsignature_planar

  stochastax:
    type: python
    script: "adapters/python/run_stochastax.py"
    extras:
      - stochastax
    backends:
      - name: cpu
        env:
          JAX_PLATFORM_NAME: cpu
      - name: gpu
        env:
          JAX_PLATFORM_NAME: gpu
    operations:
      - signature
      - logsignature
      - sigdiff
      - branchedsignature_nonplanar
      - branchedsignature_planar

  signax:
    type: python
    script: "adapters/python/run_signax.py"
    extras:
      - signax
    backends:
      - name: cpu
        env:
          JAX_PLATFORM_NAME: cpu
      - name: gpu
        env:
          JAX_PLATFORM_NAME: gpu
    operations:
      - signature
      - logsignature
      - sigdiff

  keras_sig:
    type: python
    script: "adapters/python/run_keras_sig.py"
    extras:
      - keras-sig
    backends:
      - name: cpu
        env:
          JAX_PLATFORM_NAME: cpu
      - name: gpu
        env:
          JAX_PLATFORM_NAME: gpu
    operations:
      - signature
      - sigdiff

  chen-signatures:
    type: python
    script: "adapters/python/run_chen.py"
    extras:
      - chen-signatures
    backend: cpu
    operations:
      - signature
      - logsignature
      - sigdiff

  # ChenSignatures.jl:
  #   type: julia
  #   dir: "adapters/julia"
  #   script: "run_chen.jl"
  #   operations:
  #     - signature
  #     - logsignature
