# libraries_registry.yaml
# Registry of adapters and their dependencies

libraries:
  # iisignature:
  #   type: python
  #   script: "adapters/python/run_iisignature.py"
  #   extras:
  #     - iisignature
  #   operations:
  #     - signature
  #     - logsignature

  pysiglib:
    type: python
    script: "adapters/python/run_pysiglib.py"
    extras:
      - pysiglib
    operations:
      - signature
      - logsignature
      - sigdiff
      - branchedsignature_nonplanar
      - branchedsignature_planar

  stochastax:
    type: python
    script: "adapters/python/run_stochastax.py"
    extras:
      - stochastax
    operations:
      - signature
      - logsignature
      - sigdiff
      - branchedsignature_nonplanar
      - branchedsignature_planar

  # chen-signatures:
  #   type: python
  #   script: "adapters/python/run_chen.py"
  #   extras:
  #     - chen-signatures
  #   operations:
  #     - signature
  #     - logsignature
  #     - sigdiff

  # ChenSignatures.jl:
  #   type: julia
  #   dir: "adapters/julia"
  #   script: "run_chen.jl"
  #   operations:
  #     - signature
  #     - logsignature
